packages:
  - "apps/*"
  - "packages/config/*"
  - "packages/core/*"
  - "packages/database/*"
  - "packages/microservices/*"
  - "packages/services/*"
  - "packages/state/*"
  - "packages/tests/*"
  - "packages/design/*"